# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    default_bus:
        read
    commandbus:
        read:
            middleware:
                - middleware.example_attributes
                - tactician.middleware.command_handler
